repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff
        types: [python]
        args: [--fix, --exit-non-zero-on-fix, --extend-ignore=ANN101, --extend-ignore=ANN102]
      - id: ruff-format
        types: [python]
        args: [--config, pyproject.toml]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-docstring-first
      - id: debug-statements
  - repo: local
    hooks:
      - id: ty
        name: ty-check
        entry: uv run --no-sync ty check --python=.venv/ --target-version 3.12 src/ tests/
        language: system
        pass_filenames: false
        always_run: true
        # additional_dependencies: [ty]
        # env:
        #   - ./.env
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.13.9
    hooks:
      - id: commitizen
        stages: [commit-msg]
