"""Added back_populates to different task models

Revision ID: 11524ee4d3b7
Revises: 4db568388824
Create Date: 2025-12-07 07:09:00.522177

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "11524ee4d3b7"
down_revision: str | Sequence[str] | None = "4db568388824"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
