"""Fixed typo in Valuation's tablename

Revision ID: 11f0eb05f267
Revises: 11524ee4d3b7
Create Date: 2025-12-07 09:44:26.189780
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11f0eb05f267"
down_revision: str | Sequence[str] | None = "11524ee4d3b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем существующий ENUM тип вместо создания нового
    points_type_enum = postgresql.ENUM("ACADEMIC", "REPUTATION", name="points_type_enum", create_type=False)

    op.create_table(
        "valuations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("recipient_id", sa.BigInteger(), nullable=False),
        sa.Column("giver_id", sa.BigInteger(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("points_type", points_type_enum, nullable=False),
        sa.ForeignKeyConstraint(["giver_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["recipient_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("valuation")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Аналогично для downgrade
    points_type_enum = postgresql.ENUM("ACADEMIC", "REPUTATION", name="points_type_enum", create_type=False)

    op.create_table(
        "valuation",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("recipient_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("giver_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("points_type", points_type_enum, autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["giver_id"], ["users.id"], name=op.f("valuation_giver_id_fkey"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["recipient_id"], ["users.id"], name=op.f("valuation_recipient_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("valuation_pkey")),
    )
    op.drop_table("valuations")
    # ### end Alembic commands ###
