"""Added level_type attr in Level model

Revision ID: 1ad4eff9adef
Revises: 11f0eb05f267
Create Date: 2025-12-07 22:24:39.123494

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ad4eff9adef"
down_revision: str | Sequence[str] | None = "11f0eb05f267"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "levels",
        sa.Column("level_type", postgresql.ENUM("ACADEMIC", "REPUTATION", name="points_type_enum"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("levels", "level_type")
    # ### end Alembic commands ###
