"""Splited points in to the academic and reputation ones

Revision ID: 4945016c09ea
Revises: 90fcd26bc7e1
Create Date: 2025-12-06 21:52:08.908434

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4945016c09ea"
down_revision: str | Sequence[str] | None = "90fcd26bc7e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("academic_points", sa.Integer(), nullable=False))
    op.add_column("users", sa.Column("reputation_points", sa.Integer(), nullable=False))
    op.drop_column("users", "points")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("points", sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column("users", "reputation_points")
    op.drop_column("users", "academic_points")
    # ### end Alembic commands ###
