"""Huge ORM model refactor

Revision ID: 4db568388824
Revises: 0786cd4e28e9
Create Date: 2025-12-07 06:19:00.668474

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4db568388824"
down_revision: str | Sequence[str] | None = "0786cd4e28e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "comments", "users", ["user_id"], ["id"])
    op.add_column("project_achievements", sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False))
    op.create_foreign_key(None, "project_members", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "projects", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "task_solutions", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "tasks", "users", ["user_id"], ["id"])
    points_type = postgresql.ENUM("ACADEMIC", "REPUTATION", name="points_type_enum")
    points_type.create(op.get_bind(), checkfirst=True)
    # Затем добавляем колонку, используя тот же объект points_type
    op.add_column("valuation", sa.Column("points_type", points_type, nullable=False, server_default="ACADEMIC"))
    op.alter_column("valuation", "points_type", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("valuation", "points_type")
    points_type = postgresql.ENUM("ACADEMIC", "REPUTATION", name="points_type_enum")
    points_type.drop(op.get_bind(), checkfirst=True)
    op.drop_constraint(None, "tasks", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "task_solutions", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "projects", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_constraint(None, "project_members", type_="foreignkey")  # type: ignore[arg-type]
    op.drop_column("project_achievements", "id")
    op.drop_constraint(None, "comments", type_="foreignkey")  # type: ignore[arg-type]
    # ### end Alembic commands ###
