"""Added created_at to the Valuation model

Revision ID: 62f6b2a445a5
Revises: ff7733d0c965
Create Date: 2025-12-10 00:07:21.600510

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62f6b2a445a5"
down_revision: str | Sequence[str] | None = "ff7733d0c965"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "valuations", sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("valuations", "created_at")
    # ### end Alembic commands ###
