"""Delete level_id in User model

Revision ID: 72f84561e062
Revises: efe39e88ec31
Create Date: 2025-12-09 00:49:59.547166

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72f84561e062"
down_revision: str | Sequence[str] | None = "efe39e88ec31"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("users_level_id_fkey"), "users", type_="foreignkey")
    op.drop_column("users", "level_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("level_id", sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f("users_level_id_fkey"), "users", "levels", ["level_id"], ["id"])
    # ### end Alembic commands ###
