"""Remove autoincrement

Revision ID: 799123993aca
Revises: a3feba26ccab
Create Date: 2025-12-08 22:34:10.618973

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "799123993aca"
down_revision: str | Sequence[str] | None = "a3feba26ccab"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
