"""Added date for valuation, project and task models

Revision ID: 86a3c990de2b
Revises: 62f6b2a445a5
Create Date: 2025-12-17 04:53:53.105575

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "86a3c990de2b"
down_revision: str | Sequence[str] | None = "62f6b2a445a5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
