"""Added uselist options in conections in User model

Revision ID: 8f5e51e162ce
Revises: 86a3c990de2b
Create Date: 2025-12-19 00:45:08.436748

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "8f5e51e162ce"
down_revision: str | Sequence[str] | None = "86a3c990de2b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
