"""Deleted UserTask

Revision ID: 90fcd26bc7e1
Revises: 896f0e5ed882
Create Date: 2025-12-06 21:44:08.739423

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90fcd26bc7e1"
down_revision: str | Sequence[str] | None = "896f0e5ed882"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tasks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_tasks",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("task_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("completion_status", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("user_id", "task_id", name=op.f("user_tasks_pkey")),
    )
    # ### end Alembic commands ###
