"""Added UserConstrant for the UserLevel model for fix duplication

Revision ID: efe39e88ec31
Revises: 799123993aca
Create Date: 2025-12-08 22:36:54.197872

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efe39e88ec31"
down_revision: str | Sequence[str] | None = "799123993aca"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_user_level", "user_levels", ["user_id", "level_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_user_level", "user_levels", type_="unique")
    # ### end Alembic commands ###
