"""Edited FK in User and Level models

Revision ID: ff7733d0c965
Revises: 72f84561e062
Create Date: 2025-12-09 01:06:33.081003

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "ff7733d0c965"
down_revision: str | Sequence[str] | None = "72f84561e062"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
